import { randomUUID } from 'node:crypto';
import { mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { config } from '../config.js';
import { runSudoMaybe } from './procUtil.js';

/**
 * Boot-disk btrfs snapshots, browsable/manageable from the UI - the same read-only
 * `btrfs subvolume snapshot -r /` mechanism tools/install-webui.sh's own snapshot_before_update()
 * already takes automatically before every install/update run, just also reachable on demand and
 * listable here. This module only ever lists/creates/deletes snapshots and keeps their GRUB
 * rescue-menu entries in sync - it deliberately does not offer a "reboot into this" action from
 * the UI: an earlier version did (via grub-reboot's one-shot next-boot override), but confirmed
 * live that GRUB's own "clear the override after using it" step doesn't reliably persist on this
 * btrfs setup, leaving the host stuck rebooting into the same snapshot on every subsequent plain
 * reboot until fixed by hand. Booting into a rescue snapshot for real recovery is still possible
 * exactly the way it always was - manually, from the physical GRUB menu - just not a button here.
 *
 * `@snapshots` (where every snapshot subvolume lives) sits at the *top level* (subvolid=5) of the
 * root btrfs filesystem, not inside the normally-mounted "/" subvolume (typically `@rootfs`) - so
 * reaching it always means mounting that top-level subvolume somewhere transiently first (see
 * withTopvolMounted below), the same "mount just for this operation, unmount right after" shape
 * the shell script's own trap does. Two naming prefixes share one @snapshots directory:
 * "pre-update-<stamp>" (the shell script's own automatic ones - never pruned by either side; see
 * tools/install-webui.sh's own NONRAID_SNAPSHOT_KEEP doc comment for why "keep everything" is the
 * default) and "manual-<stamp>[-<label>]" (created on demand from here, deleted explicitly).
 * Both kinds share the same GRUB rescue menu, regenerated by regenerateGrubMenu() below whenever
 * either is created or deleted from here - tools/install-webui.sh's own regeneration (on its next
 * run) was widened to include both prefixes too, so neither side clobbers the other's entries.
 */

const NAME_PATTERN = /^(pre-update|manual)-(\d{8}-\d{6})(?:-([a-zA-Z0-9-]{1,40}))?$/;
const GRUB_CFG_PATH = '/boot/grub/custom.cfg';
const GRUB_CONFIG_PATH_ON_DISK = '/boot/grub/grub.cfg';

export interface BootSnapshot {
  name: string;
  kind: 'pre-update' | 'manual';
  label: string | null;
  // The host's own local-clock timestamp embedded in the snapshot's name (matching `date
  // +%Y%m%d-%H%M%S`, the same command tools/install-webui.sh uses) - deliberately not converted
  // to a UTC instant/ISO string, since this backend has no reliable way to know the host's own
  // timezone offset relative to the value it's formatting.
  createdAtLocal: string;
  inGrubMenu: boolean;
  // Null when `btrfs filesystem du` failed or hasn't finished for this snapshot yet - never
  // blocks the rest of the listing over one slow/failed size query. See getSnapshotSize()'s own
  // doc comment for what totalBytes/exclusiveBytes actually mean for a COW btrfs snapshot.
  size: { totalBytes: number; exclusiveBytes: number } | null;
}

export async function isBtrfsRoot(): Promise<boolean> {
  try {
    const { stdout } = await runSudoMaybe('findmnt', ['-no', 'FSTYPE', '/']);
    return stdout.trim() === 'btrfs';
  } catch {
    return false;
  }
}

async function commandAvailable(bin: string): Promise<boolean> {
  try {
    await runSudoMaybe('which', [bin]);
    return true;
  } catch {
    return false;
  }
}

function formatStampForName(d: Date): string {
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

function formatStampForDisplay(stamp: string): string {
  return `${stamp.slice(0, 4)}-${stamp.slice(4, 6)}-${stamp.slice(6, 8)} ${stamp.slice(9, 11)}:${stamp.slice(11, 13)}:${stamp.slice(13, 15)}`;
}

/** Mounts the root btrfs filesystem's top-level subvolume (subvolid=5) at
 *  config.bootSnapshotsTopvolMnt for the duration of `fn`, unmounting again right after - same
 *  "mount only if not already, always try to unmount on the way out" idiom as
 *  tools/install-webui.sh's own snapshot_before_update(). Throws (rather than silently doing
 *  nothing) when root isn't btrfs at all - callers that need to degrade gracefully on a non-btrfs
 *  host check isBtrfsRoot() first instead. */
async function withTopvolMounted<T>(fn: (mnt: string) => Promise<T>): Promise<T> {
  const mnt = config.bootSnapshotsTopvolMnt;
  await mkdir(mnt, { recursive: true });
  const { stdout: rootSrc } = await runSudoMaybe('findmnt', ['-no', 'SOURCE', '/']);
  const rootDev = rootSrc.trim().split('[')[0];
  if (!rootDev) throw new Error("Could not determine the root filesystem's device.");

  let alreadyMounted = true;
  try {
    await runSudoMaybe('mountpoint', ['-q', mnt]);
  } catch {
    alreadyMounted = false;
  }
  if (!alreadyMounted) {
    await runSudoMaybe('mount', ['-o', 'subvolid=5', rootDev, mnt]);
  }
  try {
    return await fn(mnt);
  } finally {
    if (!alreadyMounted) {
      await runSudoMaybe('umount', [mnt]).catch(() => {});
    }
  }
}

/** Every `@snapshots/*` subvolume path currently on disk, in `btrfs subvolume list -o`'s own
 *  output order (oldest-created first) - "-o" scopes it to the mounted top-level subvolume only,
 *  same flag the shell script's own listing uses. */
async function listSnapshotSubvolPaths(mnt: string): Promise<string[]> {
  const { stdout } = await runSudoMaybe('btrfs', ['subvolume', 'list', '-o', mnt]).catch(() => ({ stdout: '' }));
  return stdout
    .trim()
    .split('\n')
    .filter(Boolean)
    .map((line) => line.trim().split(/\s+/).pop() ?? '')
    .filter((p) => p.startsWith('@snapshots/'));
}

/** The kernel version a snapshot has bootable files for, or null when it's missing either
 *  vmlinuz-* or the matching initrd.img-* - same "leave the snapshot on disk but don't give it a
 *  GRUB entry" degradation the shell script's own check already has. */
async function findKernelVersion(mnt: string, snapPath: string): Promise<string | null> {
  const dir = path.join(mnt, snapPath, 'boot');
  const entries = await readdir(dir).catch(() => [] as string[]);
  const vmlinuz = entries.find((f) => f.startsWith('vmlinuz-'));
  if (!vmlinuz) return null;
  const kver = vmlinuz.replace(/^vmlinuz-/, '');
  return entries.includes(`initrd.img-${kver}`) ? kver : null;
}

/**
 * `btrfs filesystem du`'s own "Total"/"Exclusive" columns for one snapshot - doesn't need btrfs
 * quotas/qgroups enabled (a much heavier, opt-in feature this app never turns on), just walks the
 * snapshot's own extent tree directly. "Total" is the snapshot's whole logical size, almost
 * entirely shared with the live filesystem and every other snapshot right after creation -
 * "Exclusive" is the part unique to this one snapshot, i.e. what deleting it would actually free.
 * Both are worth showing since Total alone reads as "deleting this frees N GB", which is normally
 * false for a fresh COW snapshot. Null on any failure (missing btrfs-progs subcommand, a snapshot
 * deleted out from under this call, etc.) - a size query failing should never fail the whole
 * listing over one entry.
 */
async function getSnapshotSize(mnt: string, snapPath: string): Promise<{ totalBytes: number; exclusiveBytes: number } | null> {
  try {
    const { stdout } = await runSudoMaybe('btrfs', ['filesystem', 'du', '--raw', '-s', path.join(mnt, snapPath)]);
    const dataLine = stdout.trim().split('\n')[1];
    const fields = dataLine?.trim().split(/\s+/) ?? [];
    const totalBytes = Number(fields[0]);
    const exclusiveBytes = Number(fields[1]);
    if (!Number.isFinite(totalBytes) || !Number.isFinite(exclusiveBytes)) return null;
    return { totalBytes, exclusiveBytes };
  } catch {
    return null;
  }
}

async function resolveGrubContext(): Promise<{ fsUuid: string; grubRootHint: string } | null> {
  try {
    const { stdout: uuidOut } = await runSudoMaybe('findmnt', ['-no', 'UUID', '/']);
    const fsUuid = uuidOut.trim();
    const grubCfg = await readFile(GRUB_CONFIG_PATH_ON_DISK, 'utf8');
    const match = grubCfg.match(/set root='([^']*)'/);
    const grubRootHint = match?.[1] ?? '';
    if (!fsUuid || !grubRootHint) return null;
    return { fsUuid, grubRootHint };
  } catch {
    return null;
  }
}

const SUBMENU_TITLE = 'NonRAID rescue snapshots';

function entryTitle(snapPath: string, kver: string): string {
  return `NonRAID rescue: ${snapPath} (Linux ${kver})`;
}

/**
 * Rebuilds /boot/grub/custom.cfg from every currently-existing snapshot with bootable kernel
 * files, exactly mirroring tools/install-webui.sh's own heredoc (down to the literal menuentry
 * body) so a GRUB entry made by either this module or that script looks identical - the only
 * difference is this always includes both "pre-update-*" and "manual-*" snapshots, where the
 * script's own regeneration (as of this feature) does too, now that both are meant to coexist in
 * the same rescue menu (manually selectable at the physical console - see this module's own doc
 * comment on why that's the only way to boot into one). Validated with grub-script-check before
 * ever touching the real file - install() only runs if that passes, so a bug here fails loudly
 * instead of corrupting the boot menu. Silently skips (returns 0) on a non-btrfs root or a host
 * with no grub-script-check, same "this is optional, not a hard requirement" reasoning the shell
 * script's own check has.
 */
async function regenerateGrubMenu(mnt: string): Promise<number> {
  const ctx = await resolveGrubContext();
  if (!ctx || !(await commandAvailable('grub-script-check'))) return 0;

  // Only names this module actually recognizes (pre-update-*/manual-*, same NAME_PATTERN
  // listBootSnapshots() filters through) - a real host can have other @snapshots/* subvolumes
  // this app never made (confirmed live: manual test snapshots from before this feature existed),
  // and those must never gain or keep a GRUB entry this UI can't show or manage.
  const paths = (await listSnapshotSubvolPaths(mnt))
    .filter((p) => NAME_PATTERN.test(p.replace(/^@snapshots\//, '')))
    .sort()
    .reverse();
  const lines: string[] = [
    "# Managed by nonraid-webui (system/bootSnapshots.ts) - regenerated whenever a boot snapshot",
    "# is created or deleted from the UI, don't hand-edit.",
    `submenu '${SUBMENU_TITLE}' {`,
  ];
  let registered = 0;
  for (const snapPath of paths) {
    const kver = await findKernelVersion(mnt, snapPath);
    if (!kver) continue;
    lines.push(
      `  menuentry '${entryTitle(snapPath, kver)}' {`,
      '    insmod part_msdos',
      '    insmod btrfs',
      `    set root='${ctx.grubRootHint}'`,
      `    search --no-floppy --fs-uuid --set=root ${ctx.fsUuid}`,
      `    echo 'Loading Linux ${kver} from ${snapPath} ...'`,
      `    linux /${snapPath}/boot/vmlinuz-${kver} root=UUID=${ctx.fsUuid} ro rootflags=subvol=${snapPath}`,
      "    echo 'Loading initial ramdisk ...'",
      `    initrd /${snapPath}/boot/initrd.img-${kver}`,
      '  }',
    );
    registered++;
  }
  lines.push('}');

  const tmpPath = path.join(os.tmpdir(), `nonraid-grub-custom-${randomUUID()}.cfg`);
  await writeFile(tmpPath, `${lines.join('\n')}\n`, 'utf8');
  try {
    await runSudoMaybe('grub-script-check', [tmpPath]);
    await runSudoMaybe('install', ['-m', '644', tmpPath, GRUB_CFG_PATH]);
  } finally {
    await unlink(tmpPath).catch(() => {});
  }
  return registered;
}

async function parseSnapshot(mnt: string, fullPath: string, customCfg: string): Promise<BootSnapshot | null> {
  const name = fullPath.replace(/^@snapshots\//, '');
  const match = name.match(NAME_PATTERN);
  if (!match) return null;
  const [, kind, stamp, label] = match;
  return {
    name,
    kind: kind as 'pre-update' | 'manual',
    label: label ?? null,
    createdAtLocal: formatStampForDisplay(stamp!),
    inGrubMenu: customCfg.includes(`/${fullPath}/boot/vmlinuz`),
    size: await getSnapshotSize(mnt, fullPath),
  };
}

/** Empty (not an error) on a non-btrfs root - same "this feature just isn't available here"
 *  degradation the routes/UI layer surfaces as a disabled state, never a failed request. Each
 *  entry's size is computed in parallel (btrfs filesystem du takes a second or so per snapshot -
 *  see getSnapshotSize()'s own doc comment), so listing several snapshots costs roughly as long
 *  as the slowest one, not their sum. */
export async function listBootSnapshots(): Promise<BootSnapshot[]> {
  if (!(await isBtrfsRoot())) return [];
  return withTopvolMounted(async (mnt) => {
    const paths = await listSnapshotSubvolPaths(mnt);
    const customCfg = await readFile(GRUB_CFG_PATH, 'utf8').catch(() => '');
    const snapshots = await Promise.all(paths.map((p) => parseSnapshot(mnt, p, customCfg)));
    return snapshots.filter((s): s is BootSnapshot => s !== null).sort((a, b) => b.name.localeCompare(a.name));
  });
}

export async function createBootSnapshot(rawLabel?: string): Promise<BootSnapshot> {
  if (!(await isBtrfsRoot())) throw new Error("Root filesystem isn't btrfs - boot snapshots aren't available on this host.");
  const label = rawLabel?.trim().replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || undefined;
  const stamp = formatStampForName(new Date());
  const name = label ? `manual-${stamp}-${label}` : `manual-${stamp}`;

  return withTopvolMounted(async (mnt) => {
    await runSudoMaybe('mkdir', ['-p', path.join(mnt, '@snapshots')]);
    await runSudoMaybe('btrfs', ['subvolume', 'snapshot', '-r', '/', path.join(mnt, '@snapshots', name)]);
    await regenerateGrubMenu(mnt);
    const customCfg = await readFile(GRUB_CFG_PATH, 'utf8').catch(() => '');
    return {
      name,
      kind: 'manual',
      label: label ?? null,
      createdAtLocal: formatStampForDisplay(stamp),
      inGrubMenu: customCfg.includes(`/@snapshots/${name}/boot/vmlinuz`),
      // Skipped here (a fresh snapshot's exclusive size is near-zero anyway) rather than paying
      // the ~1s btrfs filesystem du cost on every create - the list the UI refreshes with right
      // after shows the real number.
      size: null,
    };
  });
}

export async function deleteBootSnapshot(name: string): Promise<void> {
  if (!NAME_PATTERN.test(name)) throw new Error('Invalid snapshot name.');
  await withTopvolMounted(async (mnt) => {
    await runSudoMaybe('btrfs', ['subvolume', 'delete', path.join(mnt, '@snapshots', name)]);
    await regenerateGrubMenu(mnt);
  });
}
